### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John DomicCIS for KAFKA testing",
  "email": "kafka_testing1@example.com",
  "address": "123 older street431 with kafka ",
  "dateOfBirth": "1990-10-29",
  "registeredDate": "2024-11-17"
}

###